//create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "2111523002",
    "email": "maureen@gmail.com",
    "password": "12345",
    "confPassword": "12345",
    "role": "mahasiswa"
}

###
//get all users
GET http://localhost:5000/users

###
//get user by id
GET http://localhost:5000/users/6eae49cc-d58e-47a8-8615-19da8ddc1523

###
//update user
PATCH http://localhost:5000/users/6eae49cc-d58e-47a8-8615-19da8ddc1523
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
//delete user
DELETE http://localhost:5000/users/aa3e753b-d791-44ef-ad90-192e31992fe1

###
//login
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "2111523002",
    "password": "12345"
}

###
GET http://localhost:5000/me

###
//logout
DELETE http://localhost:5000/logout